import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(
    'c1',
    'Italian',
    Colors.purple,
  ),
  Category(
    'c2',
    'Quick & Easy',
    Colors.red,
  ),
  Category(
    'c3',
    'Hamburgers',
    Colors.orange,
  ),
  Category(
    'c4',
    'Brazilian',
    Colors.amber,
  ),
  Category(
    'c5',
    'Light & Lovely',
    Colors.blue,
  ),
  Category(
    'c6',
    'Exotic',
    Colors.green,
  ),
  Category(
    'c7',
    'Breakfast',
    Colors.lightBlue,
  ),
  Category(
    'c8',
    'Asian',
    Colors.lightGreen,
  ),
  Category(
    'c9',
    'French',
    Colors.pink,
  ),
  Category(
    'c10',
    'Summer',
    Colors.teal,
  ),
];

List<Meal> DUMMY_MEALS = [
  Meal(
    'm1',
    [
      'c1',
      'c2',
    ],
    'Spaghetti with Tomato Sauce',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    20,
    Complexity.Simple,
    Affordability.Affordable,
    false,
    true,
    true,
    true,
  ),
  Meal(
    'm2',
    [
      'c1'
          'c2',
    ],
    'Toast Hawaii',
    'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    10,
    Complexity.Simple,
    Affordability.Affordable,
    false,
    false,
    false,
    false,
  ),
  Meal(
    'm3',
    [
      'c2',
      'c3',
    ],
    'Classic Hamburger',
    'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    45,
    Complexity.Simple,
    Affordability.Pricey,
    false,
    false,
    false,
    true,
  ),
  Meal(
    'm4',
    [
      'c4',
    ],
    'Arroz de Carreteiro ',
    'https://www.comidaereceitas.com.br/wp-content/uploads/2021/08/arroz_carreteiroo-780x441.jpg',
    [
      '500 g de charque ',
      '1 colher (sopa) de óleo ',
      'meia cebola média picada',
      '2 dentes de alho amassados ',
      'meio pimentão verde picado',
      '4 tomates sem pele picados',
      '2 xícaras (chá) de água quente ',
      '1 xícara (chá) de arroz ',
      '1 tablete de MAGGI® Caldo Carne',
      'meio maço de cebolinha-verde picada ',
    ],
    [
      'Escorra a água da panela e corte a charque em cubinhos. Reserve.',
      'Em uma panela, aqueça o óleo e refogue a cebola, o alho e o pimentão.',
      'Junte a charque e deixe fritar até dourar. ',
      'Acrescente os tomates e, em seguida, o arroz. ',
      'Acrescente Caldo dissolvido na água quente para cozinhar o arroz, sem deixar secar totalmente.',
      'Acrescente a cebolinha verde e sirva.',
    ],
    60,
    Complexity.Hard,
    Affordability.Affordable,
    false,
    false,
    false,
    false,
  ),
  Meal(
    'm5',
    [
      'c2'
          'c5',
      'c10',
    ],
    'Salad with Smoked Salmon',
    'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    15,
    Complexity.Simple,
    Affordability.Luxurious,
    true,
    false,
    true,
    true,
  ),
  Meal(
    'm6',
    [
      'c6',
      'c10',
    ],
    'Delicious Orange Mousse',
    'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    240,
    Complexity.Hard,
    Affordability.Affordable,
    true,
    false,
    true,
    false,
  ),
  Meal(
    'm7',
    [
      'c7',
    ],
    'Pancakes',
    'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    20,
    Complexity.Simple,
    Affordability.Affordable,
    true,
    false,
    true,
    false,
  ),
  Meal(
    'm8',
    [
      'c8',
    ],
    'Creamy Indian Chicken Curry',
    'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    35,
    Complexity.Challenging,
    Affordability.Pricey,
    true,
    false,
    false,
    true,
  ),
  Meal(
    'm9',
    [
      'c9',
    ],
    'Chocolate Souffle',
    'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    45,
    Complexity.Hard,
    Affordability.Affordable,
    true,
    false,
    true,
    false,
  ),
  Meal(
    'm10',
    [
      'c2',
      'c5',
      'c10',
    ],
    'Asparagus Salad with Cherry Tomatoes',
    'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
    30,
    Complexity.Simple,
    Affordability.Luxurious,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm11',
    [
      'c4',
    ],
    'Feijoada',
    'https://acarnequeomundoprefere.com.br/uploads/media/image/frimesa-receitas-eisbein-1.jpg',
    [
      '1 Kg de feijão preto',
      '100 g de carne seca',
      '70 g de orelha de porco',
      '70 g de rabo de porco',
      '70 g de pé de porco',
      '100 g de costelinha de porco',
      '50 g de lombo de porco',
      '100 g de paio',
      '150 g de lingüiça portuguesa',
      'Tempero:',
      '2 cebolas grandes picadinhas',
      '1 maço de cebolinha verde picadinha',
      '3 folhas de louro',
      '6 dentes de alho',
      'Pimenta do reino a gosto',
      '1 ou 2 laranjas',
      '40 ml de de pinga',
      'Sal se precisar',
    ],
    [
      'Coloque as carnes de molho por 36 horas ou mais',
      'Vá trocando a água várias vezes, se for ambiente quente ou verão',
      'Coloque gelo por cima ou em camadas frias',
      'Coloque para cozinhar passo a passo: as carnes duras, em seguida as carnes moles',
      'Quando estiver mole coloque o feijão, e retire as carnes.',
      'Mix with asparagus, salad and dressing',
      'Finalmente tempere o feijão.'
    ],
    30,
    Complexity.Hard,
    Affordability.Affordable,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm12',
    [
      'c4',
    ],
    ' Arroz doce cremoso ',
    'https://saranossaterra.com.br/wp-content/uploads/2020/07/receita-de-arroz-doce-com-leite-condensado-9.jpg',
    [
      '1 xícaras e 1/2 de arroz',
      '2 xícaras e 1/2 de água',
      '5 xícaras de leite',
      '2 colheres de baunilha',
      '1 lata de leite condensado',
      '1 lata de creme de leite',
      'açúcar a gosto',
      'canela em pó ou em lascas',
    ],
    [
      'Coloque a água o arroz e a canela e deixe ferver até secar a água.',
      'Após coloque o leite, a baunilha, o açúcar e o leite condensado, mexendo sempre.',
      'Deixe ferver por 15 minutos e coloque o creme de leite, mexa.',
      'Ferva por mais 5 minutos e pronto.',
      'Polvilhe com canela.',
      'Pode ser servido quente ou frio conforme o gosto.',
    ],
    30,
    Complexity.Simple,
    Affordability.Pricey,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm13',
    [
      'c4',
    ],
    ' Caranguejo ao molho ',
    'https://img.cybercook.com.br/receitas/633/caranguejada-2-840x480.jpeg',
    [
      ' 6 unidades do caranguejo,',
      ' 2 tomates picados,',
      ' 1 cebola picada,',
      ' 1 maço de cheiro verde ( coentro e cebolinha) picado,',
      ' 1 pitada de tempero seco moído,',
      ' 1 colher (chá) de corante,',
      ' 2 colheres( sopa) de azeite de dendê,',
      ' 1 pimentão picado,',
      ' 3 dentes de alho amassado,',
      ' suco de 2 limões.',
      ' 2 colheres(sopa) de amido de milho ( dissolvido em um copo c/ água) e acrescente sal a gosto.',
    ],
    [
      'Limpe os caranguejos muito bem c/ uma escovinha, em água corrente. ',
      'Em uma panela grande coloque todos os ingredientes citados',
      'Cubra-os com água e deixe cozinhar bem até o ponto de tirar uma perninha e a mesma solte a carne c/ facilidade',
      'Deve ser acompanhado de um arroz temperado tipo: arroz c/ vinagreira, arroz de toucinho, etc...',
    ],
    30,
    Complexity.Simple,
    Affordability.Luxurious,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm14',
    [
      'c3',
    ],
    'Hambúrguer caseiro',
    'https://www.xl1.com.br/wp-content/uploads/2021/04/hamburguer-caseiro-1024x570.png',
    [
      '1 kg de carne moída (de preferência patinho)',
      '1 sachê de creme de cebola',
      '1 cebola media picada',
      '4 dentes de alho picado',
      'cebolinha a gosto',
      'sal e pimenta a gosto',
      'orégano a gosto',
    ],
    [
      'Misture todos os ingredientes, amasse bem e forme bolinhas, depois achate para ter a forma de hambúrguer.',
      'Frite numa frigideira antiaderente, coloque uma colher de óleo pois a carne não tem gordura.',
    ],
    30,
    Complexity.Simple,
    Affordability.Affordable,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm15',
    [
      'c3',
    ],
    'Hambúrguer de picanha com tomate assado',
    'https://s2.glbimg.com/OrHhbeGbhKxHvki5VcUN263Ot-k=/smart/e.glbimg.com/og/ed/f/original/2015/10/23/receita-casa-vieira-souto-destaque1.jpg',
    [
      '500 g de picanha',
      'Óleo vegetal pra fritar',
      'Azeite',
      '1 colher (de chá) de orégano',
      '100 g de queijo raclette',
      '250 g de tomate',
      '2 pães australianos',
      'Salada e batata frita pra acompanhar',
    ],
    [
      'Pré aqueça o forno à 200º. Limpe a carne, tirando a gordura excessiva e moa sem temperar',
      'Divida a carne em duas partes iguais, faça bolas e aperte',
      'Coloque na geladeira antes de fritar',
      'Coloque uma frigideira média no fogo com um fio de óleo, enquanto esquenta, tempere a carne com sal grosso e pimenta do reino a gosto',
      'Coloque as carnes na frigideira por 2 minutos, depois vire por 1 minuto',
      'Corte o queijo e coloque em cima da carne, leve ao forno por 1 minuto',
      'Tire do forno e acrescente o tomate assado',
    ],
    30,
    Complexity.Hard,
    Affordability.Luxurious,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm16',
    [
      'c7',
    ],
    'Pão de queijo simples',
    'https://vovopalmirinha.com.br/wp-content/uploads/2019/06/pao-de-queijo.jpg',
    [
      '400g de polvilho doce',
      '400g de queijo parmesão ralado',
      '2 caixas de creme de leite (400g) (aproximadamente)',
      'Óleo para untar',
    ],
    [
      'Em uma vasilha, junte o polvilhe doce, o parmesão e misture.',
      'Adicione o creme de leite, aos poucos, misturando com as mãos até formar uma massa homogênea e firme.',
      'É necessário que o creme de leite seja adicionado aos poucos, para não perder o ponto da massa.',
      'Retire porções pequenas da massa e modele bolinhas.',
      'Coloque, uma ao lado da outra, em uma fôrma grande untada e leve ao forno alto, preaquecido, por 15 minutos ou até dourar.',
      'Retire e sirva em seguida.',
    ],
    30,
    Complexity.Simple,
    Affordability.Pricey,
    true,
    true,
    true,
    true,
  ),
  Meal(
    'm17',
    [
      'c7',
    ],
    'Panqueca de omelete',
    'https://receitasdefamilia.net/wp-content/uploads/2021/12/Panqueca-de-Omelete-Receita-Rapida-e1639582831310.jpg',
    [
      '8 ovos',
      '4 colheres (sopa) de farinha de trigo',
      'Sal e cheiro-verde picado a gosto'
          'Manteiga para untar'
          '300g de presunto fatiado',
      '300g de queijo mussarela fatiado',
      '200g de cream cheese',
      '1/2 xícara (chá) de cheiro-verde picado',
    ],
    [
      'Em uma tigela, bata os ovos com um batedor manual até ficar aerado. ',
      'Adicione a farinha, sal, cheiro-verde e bata novamente para misturar.',
      'Aqueça uma frigideira antiaderente untada, em fogo médio, e despeje uma concha da massa. ',
      'Frite até dourar dos dois lados.',
      'Retire e repita o procedimento de concha em concha até acabar a massa.',
      'Divida o presunto, a mussarela e o cream cheese misturado com o cheiro-verde entre os discos de panqueca e enrole como rocamboles',
      'Polvilhe com cheiro-verde e sirva.',
    ],
    30,
    Complexity.Simple,
    Affordability.Pricey,
    true,
    true,
    true,
    true,
  ),
];
